### PR TITLE
Total size for topic can be a misnomer.

### PR DESCRIPTION
**Pull request by jaihind213**
It suggests size in bytes.
its actually 'total number of messages published to the topic, ever'
Better to avoid confusion.

### CODE REVIEW

**Comment by ekoutanov** [comment]
I believe most practitioners would associate topic size with the total number of published records, not bytes.

Total number of messages, ever is also incorrect, because the low-water mark will advance as the topic gets collected over time. Also, this figure contains control messages, so it's only an approximate size.

**Comment by jaihind213** [comment]
ok. The reason i raised the pr was that one of my colleagues took the number as size in bytes and did some calculations haha and we realized that something is fishy.

i put the description as 'Total number of messages, ever i' because that was the documention of the method 'getTotalSize' in 'TopicVO.java' where the number is derived from.

had a question: whats 'control messages' ?

**Comment by ekoutanov** [comment]
Control messages are deposited by Kafka for transactions, indicating that a transaction has completed or rolled back. In addition to control messages, you may also have messages that have been rolled back. (These are written to the topic, but not delivered to the consumer application, unless the latter is running with `READ_UNCOMITTED` isolation.)

**Comment by jaihind213** [comment]
thanks @ekoutanov for the answer to my qns about control messages.

i think we can close this pull request and let it remain as 'total size'.

**Comment by ekoutanov** [comment]
No probs.

**Pull request closed without merging**
