### PR TITLE
develop topic deletion service, developing controller.

### PR DESCRIPTION
**Pull request by ghost**
I have KafkaMonitorImpl and KafkaHighLevelAdminClient additions that will enable controllers to successfully delete topics. I'm not as familiar with SpringBoot MVC, so there's still a little work that needs to go into the UI. I mocked a delete button in this PR.

### CODE REVIEW

**Comment by ekoutanov** [comment]
When you say "mocked a delete button", what do you mean by that?

Also, this has raised an alert with LGTM.

**Comment by ekoutanov** [comment]
When you say "mocked a delete button", what do you mean by that?

Also, this has raised an alert with LGTM.

**Comment by ekoutanov** [comment]
When you say "mocked a delete button", what do you mean by that?

Also, this has raised an alert with LGTM.

**Comment by ghost** [comment]
> When you say "mocked a delete button", what do you mean by that?
> 
> Also, this has raised an alert with LGTM.

I just cleaned this up.

This is what the button would look like, the feature works on localhost: 

image

**Comment by ekoutanov** [comment]
Also, ideally we should style this button to look like the other buttons, for example the [+ New] button.

**Comment by ekoutanov** [comment]
Also, ideally we should style this button to look like the other buttons, for example the [+ New] button.

**Comment by ghost** [comment]
> Also, ideally we should style this button to look like the other buttons, for example the [+ New] button.

Agreed. I think the jquery dialog from #108 would fit too.

**Comment by ekoutanov** [comment]
Looked at it. Some feedback:

1. The delete button should be shown on 'internal' topics, such as `__consumer_offset`. The topic has a flag that should be checked. 
2. There is no confirmation when clicking the delete. Ideally, we should present a dialog that echoes the name of the topic and asks the user for a confirmation.
3. Upon successful deletion, we should show some notification that the action succeeded.
4. The button should be styled like the others.

**Comment by ekoutanov** [comment]
I think #108 pretty much does what we need. I'm going to merge that one first.

**Pull request closed without merging**
